package com.suraj.user_service.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Data;

@Data
public class ReportRequest {

    @NotBlank(message = "Session ID is required")
    private String sessionId;

    @NotBlank(message = "Subject is required")
    private String subject;

    private String subtopic;

    private String difficulty;

    private Integer durationMinutes;

    /**
     * The full evaluation report JSON string as generated by the LLM module.
     * Stored as-is in a JSONB column. Key fields (overallScore, skillLevel,
     * hireRecommendation) are extracted automatically by the service layer
     * into dedicated columns for efficient querying.
     */
    @NotNull(message = "Report JSON is required")
    private Object reportJson;
}
