
spring.application.name=user-service
server.port=8082


spring.datasource.url=jdbc:postgresql://fina-project-db.ct4w2y0cqw2z.ap-south-1.rds.amazonaws.com:5432/ai_interviewer
spring.datasource.username=postgres
spring.datasource.password=Project123
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


app.jwt.secret=U1VSQUpKVURFRklOQUxZRUFSUFJPSkVDVDIwMjZTRUNSRVRLRVk=
app.jwt.expiration-ms=86400000

logging.level.com.suraj.user_service=INFO
logging.level.org.springframework.security=WARN

# Resend Email (fill in your API key)
app.resend.api-key=re_7ArWNpx5_Q2LBkD4ZJmaAKw8HQDN2UGBh
app.resend.from-email=noreply@bytesnest.co.in
# Frontend URL (for password reset link)
app.frontend.url=http://localhost:3000
