package com.suraj.backend.llm.module.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * Strict JSON schema for the Evaluation Report.
 * Mirrors the exact output format defined in the Evaluator System Prompt.
 *
 * <p><strong>Overall Score Computation:</strong> The {@code overall_score} is NOT
 * generated by the LLM. It is computed deterministically by
 * {@link #computeOverallScore()} using a weighted-average formula across the
 * five sub-scores. This ensures reproducible, mathematically consistent scoring.</p>
 *
 * <h3>Weight Distribution</h3>
 * <pre>
 *   Technical Accuracy   → 30%
 *   Depth of Knowledge   → 25%
 *   Problem Solving      → 20%
 *   Clarity              → 15%
 *   Presence/Confidence  → 10%
 * </pre>
 */
@Data
@NoArgsConstructor
public class EvaluationReportDTO {

    // ── Weights for the weighted-average formula ──
    public static final double W_ACCURACY        = 0.30;
    public static final double W_DEPTH           = 0.25;
    public static final double W_PROBLEM_SOLVING = 0.20;
    public static final double W_CLARITY         = 0.15;
    public static final double W_CONFIDENCE      = 0.10;

    /**
     * Computed server-side — NOT produced by the LLM.
     * Populated by {@link #computeOverallScore()}.
     */
    private double overallScore;

    private TechnicalScores technicalScores;
    private CommunicationScores communicationScores;
    private BehavioralSummary behavioralSummary;
    private List<String> strengths;
    private List<String> weaknesses;
    private List<String> missedConcepts;
    private List<QuestionAnalysis> questionAnalysis;
    private FinalVerdict finalVerdict;

    /**
     * 7-day personalized study plan generated by the LLM based on
     * the candidate's missed concepts and weaknesses.
     */
    private List<StudyPlanDay> studyPlan;

    /**
     * Breakdown showing how each parameter contributed to the overall score.
     * Injected into the JSON so the frontend can render the formula.
     */
    private ScoreBreakdown scoreBreakdown;

    // ──────────────────────────────────────────────────────────────
    //  Weighted Score Computation
    // ──────────────────────────────────────────────────────────────

    /**
     * Computes the overall score (0–100) as a weighted average of the five
     * sub-scores (each 0–10), and populates the {@link #scoreBreakdown} field.
     *
     * <pre>
     * overallScore = (w₁×accuracy + w₂×depth + w₃×problemSolving
     *              + w₄×clarity + w₅×confidence) × 10
     * </pre>
     *
     * @return the computed overall score, rounded to 2 decimal places
     */
    public double computeOverallScore() {
        double accuracy       = safe(technicalScores != null ? technicalScores.getAccuracy() : 0);
        double depth          = safe(technicalScores != null ? technicalScores.getDepth() : 0);
        double problemSolving = safe(technicalScores != null ? technicalScores.getProblemSolving() : 0);
        double clarity        = safe(communicationScores != null ? communicationScores.getClarity() : 0);
        double confidence     = safe(communicationScores != null ? communicationScores.getConfidence() : 0);

        double weightedSum = W_ACCURACY * accuracy
                           + W_DEPTH * depth
                           + W_PROBLEM_SOLVING * problemSolving
                           + W_CLARITY * clarity
                           + W_CONFIDENCE * confidence;

        double computed = round2(weightedSum * 10);

        // Build the breakdown for frontend display
        this.scoreBreakdown = ScoreBreakdown.builder()
                .accuracy(ScoreBreakdown.ParameterContribution.builder()
                        .parameter("Technical Accuracy")
                        .rawScore(accuracy)
                        .weight(W_ACCURACY)
                        .weightedContribution(round2(W_ACCURACY * accuracy * 10))
                        .build())
                .depth(ScoreBreakdown.ParameterContribution.builder()
                        .parameter("Depth of Knowledge")
                        .rawScore(depth)
                        .weight(W_DEPTH)
                        .weightedContribution(round2(W_DEPTH * depth * 10))
                        .build())
                .problemSolving(ScoreBreakdown.ParameterContribution.builder()
                        .parameter("Problem Solving")
                        .rawScore(problemSolving)
                        .weight(W_PROBLEM_SOLVING)
                        .weightedContribution(round2(W_PROBLEM_SOLVING * problemSolving * 10))
                        .build())
                .clarity(ScoreBreakdown.ParameterContribution.builder()
                        .parameter("Clarity")
                        .rawScore(clarity)
                        .weight(W_CLARITY)
                        .weightedContribution(round2(W_CLARITY * clarity * 10))
                        .build())
                .confidence(ScoreBreakdown.ParameterContribution.builder()
                        .parameter("Presence & Confidence")
                        .rawScore(confidence)
                        .weight(W_CONFIDENCE)
                        .weightedContribution(round2(W_CONFIDENCE * confidence * 10))
                        .build())
                .formula("overallScore = (0.30 × Accuracy + 0.25 × Depth + 0.20 × Problem Solving + 0.15 × Clarity + 0.10 × Confidence) × 10")
                .computedScore(computed)
                .build();

        this.overallScore = computed;
        return computed;
    }

    private static double safe(double value) {
        return Double.isFinite(value) ? Math.max(0, Math.min(10, value)) : 0;
    }

    private static double round2(double value) {
        return Math.round(value * 100.0) / 100.0;
    }

    // ──────────────────────────────────────────────────────────────
    //  Inner DTOs
    // ──────────────────────────────────────────────────────────────

    @Data
    @NoArgsConstructor
    public static class TechnicalScores {
        private double accuracy;
        private double depth;
        private double problemSolving;
    }

    @Data
    @NoArgsConstructor
    public static class CommunicationScores {
        private double clarity;
        private double confidence;
    }

    @Data
    @NoArgsConstructor
    public static class BehavioralSummary {
        private String confidenceLevel;   // "High", "Med", "Low"
        private String observations;
    }

    @Data
    @NoArgsConstructor
    public static class QuestionAnalysis {
        private String question;
        private String rating;            // "Correct", "Partial", "Wrong"
        private String justification;
    }

    @Data
    @NoArgsConstructor
    public static class FinalVerdict {
        private String skillLevel;        // "Beginner", "Intermediate", "Advanced"
        private String hireRecommendation; // "Yes", "No", "Maybe"
        private String summary;
    }

    /**
     * One day in the 7-day study plan. Each day targets a specific
     * weak area identified during the interview.
     */
    @Data
    @NoArgsConstructor
    public static class StudyPlanDay {
        private int day;                  // 1-7
        private String topic;             // e.g. "HashMap Internals"
        private String focus;             // Brief description of what to study
        private List<String> tasks;       // Concrete study tasks / exercises
    }

    /**
     * Captures the full breakdown of how the overall score was computed.
     * Sent to the frontend so users can see exactly how their score was derived.
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class ScoreBreakdown {
        private ParameterContribution accuracy;
        private ParameterContribution depth;
        private ParameterContribution problemSolving;
        private ParameterContribution clarity;
        private ParameterContribution confidence;
        private String formula;
        private double computedScore;

        @Data
        @Builder
        @NoArgsConstructor
        @AllArgsConstructor
        public static class ParameterContribution {
            /** Human-readable parameter name, e.g. "Technical Accuracy" */
            private String parameter;
            /** Raw LLM score on the 0–10 scale */
            private double rawScore;
            /** Weight used in the formula, e.g. 0.30 */
            private double weight;
            /** Contribution to the final 0–100 score: weight × rawScore × 10 */
            private double weightedContribution;
        }
    }
}
